#ifndef _Opydome_H_
#define _Opydome_H_

enum {
    PYDOME_GROUP_MAIN                   = 10000,
        PYDOME_BOOL_BACKGROUND,
        PYDOME_BOOL_ENVIRONMENT,
        PYDOME_BOOL_REFLECTION,
        PYDOME_BOOL_SUN,
        PYDOME_BOOL_LIGHTS,
        PYDOME_BTN_LOAD,

    PYDOME_GROUP_INFO                   = 10100,
        PYDOME_STATIC_NAME,
        PYDOME_STATIC_AUTHOR,
        PYDOME_STATIC_LINK,
        PYDOME_STATIC_LOCATION,
        PYDOME_TEXT_COMMENT,
        PYDOME_STATIC_LAT,
        PYDOME_STATIC_LON,
        PYDOME_STATIC_DATE,
        PYDOME_STATIC_TIME,

    PYDOME_GROUP_ENVIRONMENT            = 10200,
        PYDOME_ENV_LINK_PROTOTYPE,
        PYDOME_ENV_BOOL_USESRGB,
        PYDOME_ENV_LONG_SEED,
        PYDOME_ENV_REAL_RADIUS,
        PYDOME_ENV_LONG_SAMPLES,
        PYDOME_ENV_REAL_THRESHOLD,
        PYDOME_ENV_REAL_HORIZON,
        PYDOME_ENV_BOOL_NORMALIZE,
        PYDOME_ENV_REAL_MULTIPLIER,

    _PYDOME_DUMMY
};

#endif