CONTAINER Opydome                           {
    NAME Opydome;
    INCLUDE Obase;
    GROUP PYDOME_GROUP_MAIN                 {
        DEFAULT 1;
        GROUP                               {
            COLUMNS 3;
            BOOL PYDOME_BOOL_BACKGROUND     {ANIM OFF;}
            BOOL PYDOME_BOOL_ENVIRONMENT    {ANIM OFF;}
            BOOL PYDOME_BOOL_REFLECTION     {ANIM OFF;}
            BOOL PYDOME_BOOL_SUN            {ANIM OFF;}
            BOOL PYDOME_BOOL_LIGHTS         {ANIM OFF;}
        }
        BUTTON PYDOME_BTN_LOAD              {}
        SEPARATOR                           {LINE;}
        LINK PYDOME_ENV_LINK_PROTOTYPE      {ACCEPT {Olight;}}
        BOOL PYDOME_ENV_BOOL_USESRGB        {}
        LONG PYDOME_ENV_LONG_SEED           {MIN 0; MINSLIDER 0; MAXSLIDER 1000; CUSTOMGUI LONGSLIDER;}
        REAL PYDOME_ENV_REAL_RADIUS         {MIN 1.0; STEP 1.0; MINSLIDER 1.0; MAXSLIDER 5000.0; UNIT METER; CUSTOMGUI REALSLIDER;}
        LONG PYDOME_ENV_LONG_SAMPLES        {MIN 1; MAX 9999; MINSLIDER 1; MAXSLIDER 500; CUSTOMGUI LONGSLIDER;}
        REAL PYDOME_ENV_REAL_THRESHOLD      {MIN 0.0; STEP 0.01; MINSLIDER 0.0; MAXSLIDER 1.0; CUSTOMGUI REALSLIDER;}
        REAL PYDOME_ENV_REAL_HORIZON        {MIN 0.0; MAX 1.0; STEP 0.01; CUSTOMGUI REALSLIDER;}
        REAL PYDOME_ENV_REAL_MULTIPLIER     {MIN 0.0; MAX 10.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.001; CUSTOMGUI REALSLIDER;}
        BOOL PYDOME_ENV_BOOL_NORMALIZE      {}
    }
    GROUP PYDOME_GROUP_INFO                 {
        SCALE_V;
        STATICTEXT PYDOME_STATIC_NAME       {}
        STATICTEXT PYDOME_STATIC_AUTHOR     {}
        STATICTEXT PYDOME_STATIC_LINK       {}
        STATICTEXT PYDOME_STATIC_LOCATION   {}
        STATICTEXT PYDOME_STATIC_LAT        {}
        STATICTEXT PYDOME_STATIC_LON        {}
        STATICTEXT PYDOME_STATIC_DATE       {}
        STATICTEXT PYDOME_STATIC_TIME       {}
        STRING PYDOME_TEXT_COMMENT          {ANIM OFF; CUSTOMGUI MULTISTRING; SCALE_V;}
    }
}
